services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FrontendPermissionToolkitBundle\GenericDataIndex\FieldDefinitionAdapter\PermissionResourceAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "permissionResource" }

    FrontendPermissionToolkitBundle\GenericDataIndex\FieldDefinitionAdapter\DynamicPermissionResourceAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "dynamicPermissionResource" }

    FrontendPermissionToolkitBundle\GenericDataIndex\FieldDefinitionAdapter\PermissionRelationAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "permissionManyToManyRelation" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "permissionManyToOneRelation" }