services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    pimcore.front_permission_toolkit.generic_data_index.data_object.relation-adapter:
        class: Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\DefaultSearch\DataObject\FieldDefinitionAdapter\RelationAdapter
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "permissionManyToManyRelation" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "permissionManyToOneRelation" }

    pimcore.front_permission_toolkit.generic_data_index.data_object.dynamic-permission-resource-adapter:
        class: Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\DefaultSearch\DataObject\FieldDefinitionAdapter\TextKeywordAdapter
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "permissionResource" }

    FrontendPermissionToolkitBundle\GenericDataIndex\FieldDefinitionAdapter\DynamicPermissionResourceAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "dynamicPermissionResource" }
