services:

    FrontendPermissionToolkitBundle\Service:
        public: true
        autoconfigure: true
        autowire: true

    bundle.frontendpermissiontoolkit.service:
        alias: FrontendPermissionToolkitBundle\Service

    FrontendPermissionToolkitBundle\EventSubscriber\CustomLayoutSubscriber:
        tags:
            - { name: kernel.event_subscriber }