name: "Static Analysis centralized"

on:
  schedule:
        - cron: '0 4 * * 1,3,5'
  pull_request:
    branches:
      - "[0-9]+.[0-9]+"
      - "[0-9]+.x"
  push:
    branches:
      - "[0-9]+.[0-9]+"
      - "[0-9]+.x"

jobs:
  static-analysis-phpstan:
    name: "Static Analysis with PHPStan"
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-static-analysis-unified.yaml@reusable-workflows
    with:
      phpstan_matrix: >-
        {"include":[
          {"php-version":"8.3","dependencies":"lowest","experimental":false},
          {"php-version":"8.4","dependencies":"highest","experimental":false},
          {"php-version":"8.4","dependencies":"highest","pimcore_version":"12.x-dev as 12.0.0","experimental":true}
        ]}

      private_repo: ${{ github.event.repository.private }}
      APP_ENV: test
      PIMCORE_TEST: "false"
      REQUIRE_ADMIN_BUNDLE: "false"
      COVERAGE: "none"
      INSTALL_PIMCORE: "true"
    secrets:
      SSH_PRIVATE_KEY_PIMCORE_DEPLOYMENTS_USER: ${{ secrets.SSH_PRIVATE_KEY_PIMCORE_DEPLOYMENTS_USER }}
      COMPOSER_PIMCORE_REPO_PACKAGIST_TOKEN: ${{ secrets.COMPOSER_PIMCORE_REPO_PACKAGIST_TOKEN }}
      PIMCORE_CI_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_CI_INSTANCE_IDENTIFIER }}
      PIMCORE_CI_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_CI_ENCRYPTION_SECRET }}
      PIMCORE_CI_PRODUCT_KEY: ${{ secrets.PIMCORE_CI_PRODUCT_KEY }}
